### ISSUE TITLE
Using mlock() to avoid sensitive data being written to swap space

### ISSUE THREAD

**Issue by brycx** [jsfierro/jfpg#4]
I think it would be a good idea to use [mlock()](https://linux.die.net/man/2/mlock) for things like passwords, or loaded private keys, to avoid them being written to the swap space.

**Comment by jsfierro** [comment]
It used to IIRC, but there was a problem on some platforms. I'll take a look and see if I can reproduce it with the current code. It would definitely be preferable to use it though.

**Comment by jsfierro** [comment]
See commit 02a757ae09649eaad2e7481427cc5b30fb388cbf

Will need testing on other operating systems and architectures, but it seems to work fine.

**Comment by brycx** [comment]
Looking good.

**Comment by jsfierro** [comment]
This is working for me but it means we can't use pledge() on OpenBSD, which is disappointing. A better method is needed for either the mlock() placement or pledge() usage. A different issue for a different day, perhaps. 

I'm closing this issue for now since there were no other problems reported with mlock().
